# Generated by Django 4.2.4 on 2023-09-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='bet',
            name='type',
            field=models.CharField(choices=[('Straight', 'Straight'), ('Parlay', 'Parlay')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bets',
            field=models.ManyToManyField(to='accounts.bet'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
