# Generated by Django 4.2.4 on 2023-09-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_user_product_match_id_alter_order_to_win'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='match_date',
            new_name='commence_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='key',
            field=models.CharField(choices=[('h2h', 'h2h'), ('spreads', 'spreads'), ('totals', 'totals')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='match_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sport_title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='winner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
