# Generated by Django 4.2.4 on 2023-09-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_cartitem_wager_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=150, null=True)),
                ('sport_group', models.CharField(max_length=150, null=True)),
                ('sport_title', models.CharField(max_length=150, null=True)),
                ('match_name', models.CharField(max_length=200, null=True)),
                ('team1', models.CharField(max_length=200, null=True)),
                ('team2', models.CharField(max_length=200, null=True)),
                ('commence_time', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='commence_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='match_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sport_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sport_title',
        ),
        migrations.AddField(
            model_name='product',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.match'),
        ),
    ]
