# Generated by Django 4.2.4 on 2023-09-25 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_match_remove_product_commence_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='sport_group',
            new_name='league',
        ),
        migrations.AlterField(
            model_name='product',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.match'),
        ),
    ]
