# Generated by Django 4.2.4 on 2023-09-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='max_wager',
            field=models.FloatField(null=True),
        ),
    ]
