# Generated by Django 4.2.4 on 2023-09-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_orderitem_max_wager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Wager Won', 'Wager Won'), ('Wager Lost', 'Wager Lost'), ('Draw', 'Draw'), ('Cart', 'Cart'), ('Void', 'Void')], default='Pending', max_length=50, null=True),
        ),
    ]
