# Generated by Django 4.2.4 on 2023-09-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_product_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_data',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
