# Generated by Django 4.2.4 on 2023-10-06 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Wager Won', 'Wager Won'), ('Wager Lost', 'Wager Lost'), ('Draw', 'Draw'), ('Void', 'Void')], default='Pending', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('Straight', 'Straight'), ('Parlay', 'Parlay')], max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('products', models.ManyToManyField(null=True, to='accounts.product')),
            ],
        ),
    ]
