# Generated by Django 4.2.4 on 2023-10-09 01:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_order_is_ordered_alter_order_status_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_type',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wager', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('wager_type', models.CharField(choices=[('Straight', 'Straight'), ('Parlay', 'Parlay')], default='Straight', max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(null=True, to='accounts.cartitem'),
        ),
    ]
