# Generated by Django 4.2.4 on 2023-10-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_cart_order_type_cartitem_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.cartitem'),
        ),
    ]
